- name: variables
  hosts: local
  connection: local
  vars:
    my_variable: "This is a variable"
  tasks:
  - name: print the value of variable
    ansible.builtin.debug:
      msg: "The value of variable is {{ my_variable }}"
