- name: Variables from files
  hosts: local
  connection: local
  vars_files: 
  - var.yaml
  tasks:
  - name: include variables from file
    ansible.builtin.include_vars:
      msg: "COURSE is {{ COURSE }}, DURATION is {{ DURATION }} and TRAINER is {{ TRAINER }}"